# Configuration for Jekyll
safe: false
source: .
destination: ./_site
lsi: false
kramdown:
  input: GFM
excerpt_separator: <!--more-->
sass:
  sass_dir: ./_sass

# Configuration for site
title: I Made a Thing!
description: A personal log of the Things I've Made
author: Twulz
url: https://twulz.github.com
baseurl: ""
repository: "Twulz/Twulz.github.io"
lang: EN-AU

# Configuration for blog
lang: en
paginate: 10
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200
recent_posts: 10

# Configuration for navbar
navbar_list:
- name: Home
  link: /
- name: Blog
  link: /blog/
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives
  - name: Categories
    link: /blog/categories
  - name: Tags
    link: /blog/tags
- name: Things
  link: /things/
  dropdown: &dropdown
  - name: Engineering Things
    link: /engprojects/
  - name: Miniature Things
    link: /mini/
  - name: Gardening Things
    link: /garden/
- name: About
  link: /about.html

navbar_list_large:
- name: Home
  link: /
- name: Blog
  link: /blog/
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives
  - name: Categories
    link: /blog/categories
  - name: Tags
    link: /blog/tags
- name: 'Things:'
  link: /things/
- name: Mechatronics
  link: /things/mechatronics/
  dropdown: &dropdown
  - name: All-In-One Server
    link: /things/software/server/
  - name: Basil the DonkeyCar
    link: /things/mechatronics/donkeycar/
  - name: Final Year Projects
    link: /things/mechatronics/fyp/
  - name: Prusa i3 3D Printer
    link: /things/mechatronics/printer/
  - name: Orrery
    link: /things/mechatronics/orrery/
  - name: 4x4x4 LED Cube
    link: /things/mechatronics/cube4x4x4/
  - name: Other Engineering Things
    link: /things/mechatronics/other/
- name: Software
  link: /things/software/
  dropdown: &dropdown
  - name: All-In-One Server
    link: /things/software/server/
  - name: I Made a Thing! Blog
    link: /things/software/blog
  - name: Final Year Projects
    link: /things/mechatronics/fyp/
- name: Miniature
  link: /things/mini/
  dropdown: &dropdown
  - name: Zombicide Painting
    link: /things/mini/zombicide/
  - name: Dark Souls Board Game Painting
    link: /things/mini/darksouls/
- name: Garden
  link: /things/garden/
  dropdown: &dropdown
  - name: Vegepod
    link: /things/garden/vegepod/
  - name: Other Garden Things
    link: /things/garden/other/
#- name: Sewing
#  link: /sewing/
#- name: Misc
#  link: /misc/
#- name: About
#  link: /about/

# Configuration for navbar.html
# navbar_list:
# - name: Blog
#   link: /
#   dropdown: &dropdown
#   - name: Archives
#     link: /blog/archives.html
#   - name: Categories
#     link: /blog/categories.html
#   - name: Tags
#     link: /blog/tags.html
# - name: Engineering Things
#   link: /engprojects/
#   dropdown: &dropdown
#   - name: All-In-One Server
#     link: /engprojects/server/
#   - name: Basil the DonkeyCar
#     link: /engprojects/donkeycar/
#   - name: Final Year Projects
#     link: /engprojects/fyp/
#   - name: Orrery
#     link: /engprojects/orrery/
#   - name: Prusa i3 3D Printer
#     link: /engprojects/printer/
#   - name: I Made a Thing! Blog
#     link: /engprojects/jekyll-blog
#   - name: 4x4x4 LED Cube
#     link: /engprojects/cube4x4x4/
#   - name: Other Engineering Things
#     link: /engprojects/other/
# - name: Games Things
#   link: /games/
#   dropdown: &dropdown
#   - name: Zombicide Painting
#     link: /games/zombicide/
#   - name: Dark Souls Board Game Painting
#     link: /games/darksouls/
# - name: Gardening Things
#   link: /garden/
#   dropdown: &dropdown
#   - name: Vegepod
#     link: /garden/vegepod/
#   - name: Other Garden Things
#     link: /garden/other/
# - name: Links
#   link: /useful-links.html
# - name: About
#   link: /about.html

plugins:
#  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

# Configuration for asides.html
# asides:
#     about: true
#     search: false
#     themes: false
#     recent_posts: true
#     archive_tabs: true
#     tweets: true
#     github: true